name: simlingo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2025.1.31=hbcca054_0
  - comm=0.2.1=py38h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - gh=2.67.0=h76a2195_0
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - jupyter_client=7.4.9=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - python=3.8.18=h955ad1f_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==1.0.1
    - adal==1.2.7
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - ansicolors==1.1.8
    - antlr4-python3-runtime==4.9.3
    - anyio==4.5.2
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - asyncio-atexit==1.0.1
    - attrs==23.2.0
    - azure-common==1.1.28
    - azure-core==1.30.0
    - azure-identity==1.14.0
    - azure-keyvault==4.2.0
    - azure-keyvault-certificates==4.8.0
    - azure-keyvault-keys==4.9.0
    - azure-keyvault-secrets==4.8.0
    - azure-nspkg==3.0.2
    - azure-storage-blob==12.18.1
    - carla==0.9.15
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - cramjam==2.8.2
    - cryptography==42.0.4
    - cycler==0.12.1
    - debugpy==1.8.1
    - deepdiff==6.7.1
    - deepspeed==0.16.2
    - diskcache==5.4.0
    - dictor==0.1.12
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - elementpath==1.3.3
    - ephem==4.1.5
    - exceptiongroup==1.2.2
    - fastjsonschema==2.21.1
    - fastparquet==2024.2.0
    - filelock==3.13.1
    - filterpy==1.4.5
    - fonttools==4.48.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - gym==0.26.2
    - gym-notices==0.0.8
    - h11==0.16.0
    - h5py==3.10.0
    - hjson==3.1.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.27.0
    - hydra-core==1.3.2
    - hydra-zen==0.12.1
    - idna==3.6
    - imageio==2.34.0
    - imgaug==0.4.0
    - immutabledict==4.1.0
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - isodate==0.6.1
    - jinja2==3.1.3
    - jiter==0.9.0
    - joblib==1.3.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - laspy==2.5.3
    - laszip==0.2.3
    - lazrs==0.5.3
    - lazy-loader==0.3
    - lightning==2.3.3
    - lightning-utilities==0.10.1
    - line-profiler==4.1.2
    - lxml==5.3.0
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - mpmath==1.3.0
    - msal==1.27.0
    - msal-extensions==1.1.0
    - msgpack==1.1.0
    - msrest==0.7.1
    - msrestazure==0.6.4
    - multidict==6.0.5
    - nbclient==0.10.1
    - nbformat==5.10.4
    - networkx==3.1
    - ninja==1.11.1.1
    - numpy==1.23.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - onnx==1.15.0
    - openai==1.76.0
    - opencv-python==4.2.0.32
    - ordered-set==4.1.0
    - orjson==3.10.15
    - packaging==23.2
    - pandas==2.0.3
    - papermill==2.6.0
    - peft==0.13.2
    - pexpect==4.9.0
    - pillow==10.2.0
    - pkgutil-resolve-name==1.3.10
    - portalocker==2.8.2
    - protobuf==4.25.3
    - psutil==5.9.8
    - py==1.11.0
    - py-cpuinfo==9.0.0
    - py-trees==0.8.3
    - pyarrow==15.0.1
    - pycparser==2.21
    - pydantic==2.6.1
    - pydantic-core==2.16.2
    - pydot==2.0.0
    - pygame==2.5.2
    - pyjwt==2.8.0
    - pynvml==11.5.0
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==2.4.0
    - pytz==2024.1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - rdp==0.8
    - referencing==0.35.1
    - regex==2023.12.25
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - retry==0.9.2
    - rpds-py==0.20.1
    - safetensors==0.5.2
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - send2trash==1.8.2
    - sentry-sdk==1.40.5
    - setproctitle==1.3.3
    - shapely==1.7.1
    - simple-watchdog-timer==0.1.1
    - smmap==5.0.1
    - sniffio==1.3.1
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==9.0.0
    - termcolor==2.4.0
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - timm==0.9.16
    - tokenizers==0.20.3
    - torch==2.2.0
    - torchaudio==2.2.0
    - torchdata==0.7.1
    - torchmetrics==1.3.1
    - torchvision==0.17.0
    - tqdm==4.66.2
    - transformers==4.46.3
    - transforms3d==0.4.1
    - triton==2.2.0
    - typing-extensions>=4.11.0,<5.0
    - tzdata==2024.1
    - ujson==5.9.0
    - urllib3==2.2.0
    - wandb==0.16.3
    - webcolors==1.13
    - xmlschema==1.0.18
    - yarl==1.9.4
    - zipp==3.17.0
